// frontend/src/pages/RoundsPage.tsx
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { Plus } from "lucide-react";
import clsx from "clsx/lite";
import IfAdmin from "@/components/IfAdmin";
import ErrorState from "@/components/ErrorState";
import GreenButton from "@/components/GreenButton";
import LoadingState from "@/components/LoadingState";
import PageContainer from "@/components/PageContainer";
import RoundCard from "@/components/RoundCard";
import RoundsPageHeader from "@/components/RoundsPageHeader";
import { useRoundsQuery } from "@/queries/rounds";
import { useCreateRoundMutation } from "@/mutations/rounds";

const RoundsPage: React.FC = () => {
  const navigate = useNavigate();

  const {
    data: rounds,
    error,
    isLoading,
    isSuccess,
    refetch,
  } = useRoundsQuery();

  const createMutation = useCreateRoundMutation(
    (data) => {
      toast.success("Раунд создан!");
      navigate(`/rounds/${data.id}`);
    },
    () => {
      toast.error("Ошибка создания раунда");
    }
  );

  return (
    <PageContainer>
      <RoundsPageHeader />

      <div className={clsx("space-y-6")}>
        <IfAdmin>
          <GreenButton
            title={createMutation.isPending ? "Создание..." : "Создать раунд"}
            onClick={() => createMutation.mutate()}
            disabled={createMutation.isPending}
            icon={<Plus className={clsx("w-5", "h-5")} />}
          />
        </IfAdmin>

        {isLoading && <LoadingState />}

        {error && <ErrorState />}

        {isSuccess && (
          <div className={clsx("space-y-6")}>
            {rounds.length === 0 ? (
              <div className={clsx("text-center", "py-12")}>
                <div className={clsx("text-gray-400", "text-lg")}>
                  Раундов пока нет
                </div>
                <IfAdmin>
                  <p className={clsx("text-gray-500", "mt-2")}>
                    Создайте первый раунд
                  </p>
                </IfAdmin>
              </div>
            ) : (
              rounds.map((round) => (
                <RoundCard
                  key={round.id}
                  round={round}
                  onClick={() => navigate(`/rounds/${round.id}`)}
                  onTimeout={refetch}
                />
              ))
            )}
          </div>
        )}
      </div>
    </PageContainer>
  );
};

export default RoundsPage;

// frontend-vue/src/pages/RoundsPage.vue
<script setup lang="ts">
import { computed } from "vue";
import { useRouter } from "vue-router";
import { Plus } from "lucide-vue-next";
import { toast } from "@steveyuowo/vue-hot-toast";
import ErrorState from "@/components/ErrorState.vue";
import GreenButton from "@/components/GreenButton.vue";
import IfAdmin from "@/components/IfAdmin.vue";
import LoadingState from "@/components/LoadingState.vue";
import NoRoundsBlock from "@/components/NoRoundsBlock.vue";
import PageContainer from "@/components/PageContainer.vue";
import RoundCard from "@/components/RoundCard.vue";
import RoundsPageHeader from "@/components/RoundsPageHeader.vue";
import { useRoundsQuery } from "@/queries/rounds";
import { useCreateRoundMutation } from "@/mutations/rounds";

const router = useRouter();

const { data: rounds, error, isLoading, isSuccess, refetch } = useRoundsQuery();

const createMutation = useCreateRoundMutation(
  (data) => {
    toast.success("Раунд создан!");
    router.push(`/rounds/${data.id}`);
  },
  () => {
    toast.error("Ошибка создания раунда");
  },
);

const createButtonTitle = computed(() =>
  createMutation.isPending.value ? "Создание..." : "Создать раунд",
);

const hasRounds = computed(
  () => Array.isArray(rounds.value) && rounds.value.length > 0,
);
</script>

<template>
  <PageContainer>
    <RoundsPageHeader />

    <div class="space-y-6">
      <IfAdmin>
        <GreenButton
          :title="createButtonTitle"
          :disabled="createMutation.isPending.value"
          @click="createMutation.mutate"
        >
          <template #icon>
            <Plus class="h-5 w-5" />
          </template>
        </GreenButton>
      </IfAdmin>

      <LoadingState v-if="isLoading" />
      <ErrorState v-if="error" />

      <template v-if="isSuccess">
        <template v-if="hasRounds">
          <RoundCard
            v-for="round in rounds"
            :key="round.id"
            :round="round"
            :on-timeout="refetch"
            @click="router.push(`/rounds/${round.id}`)"
          >
            {{ round.id }}
          </RoundCard>
        </template>
        <NoRoundsBlock v-else />
      </template>
    </div>
  </PageContainer>
</template>
