// frontend-vue/src/components/FloatableText.vue
<script setup lang="ts">
interface Props {
  accent: boolean;
  label: string;
  x: number;
  y: number;
}

export interface Floatable extends Props {
  key: number;
}

interface Emits {
  (e: "finish"): void;
}

defineProps<Props>();
const emit = defineEmits<Emits>();
</script>

<template>
  <Transition appear name="floatable" @after-enter="emit('finish')">
    <div
      class="pointer-events-none absolute text-2xl font-bold"
      :class="accent ? 'text-green-500' : 'text-white'"
      :style="{
        left: x + 'px',
        top: y + 'px',
        '--from-scale': accent ? '2' : '1',
        '--to-scale': accent ? '3' : '1.5',
      }"
    >
      {{ label }}
    </div>
  </Transition>
</template>

<style scoped>
.floatable-enter-active {
  transition:
    transform 2s ease-out,
    opacity 2s ease-out;
}

.floatable-enter-from {
  opacity: 1;
  transform: translate(-50%, -50%) scale(var(--from-scale));
}

.floatable-enter-to {
  opacity: 0;
  transform: translate(-50%, -200px) scale(var(--to-scale));
}
</style>

// frontend/src/components/FloatableText.tsx
import { type FC } from "react";
import { motion } from "framer-motion";
import clsx from "clsx/lite";

export interface Floatable {
  accent: boolean;
  key: number;
  label: string;
  x: number;
  y: number;
}

export interface FloatableTextProps extends Floatable {
  onComplete: () => void;
}

const FloatableText: FC<FloatableTextProps> = ({
  x,
  y,
  label,
  accent,
  onComplete,
}) => (
  <motion.div
    initial={{ opacity: 1, y: 0, scale: accent ? 2 : 1 }}
    animate={{ opacity: 0, y: -150, scale: accent ? 3 : 1.5 }}
    exit={{ opacity: 0 }}
    transition={{ duration: 2, ease: "easeOut" }}
    className={clsx(
      "absolute pointer-events-none font-bold text-2xl",
      accent ? "text-green-500" : "text-white"
    )}
    style={{ left: x, top: y, transform: "translate(-50%, -50%)" }}
    onAnimationComplete={onComplete}
  >
    {label}
  </motion.div>
);

export { FloatableText };
