// frontend-vue/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { Lock, User } from "lucide-vue-next";
import { toast } from "@steveyuowo/vue-hot-toast";
import PurpleButton from "@/components/PurpleButton.vue";
import { useLoginMutation } from "@/mutations/auth";

const username = ref("");
const password = ref("");

const loginMutation = useLoginMutation(
  () => {
    toast.success("Добро пожаловать в игру!");
  },
  () => {
    toast.error("Ошибка входа");
  },
);

const buttonTitle = computed(() =>
  loginMutation.isPending.value ? "Вход..." : "Войти",
);

const handleSubmit = async () => {
  if (!username.value.trim() || !password.value.trim()) {
    toast.error("Пожалуйста, заполните все поля");
    return;
  }

  loginMutation.mutate({ username: username.value, password: password.value });
};
</script>

<template>
  <div class="flex min-h-screen items-center justify-center p-4">
    <div class="w-full max-w-md">
      <div
        class="space-y-4 p-4 sm:rounded-2xl sm:border sm:border-white/20 sm:bg-white/10 sm:p-8 sm:shadow-2xl sm:backdrop-blur-lg"
      >
        <div class="text-center">
          <h1 class="mb-2 text-3xl font-bold text-white">The Last of Guss</h1>
          <p class="text-gray-300">Войдите, чтобы начать игру</p>
        </div>

        <form class="space-y-6" @submit.prevent="handleSubmit">
          <div>
            <label
              for="username"
              class="mb-2 block text-sm font-medium text-gray-200"
            >
              Имя пользователя
            </label>
            <div class="relative">
              <User
                class="absolute top-1/2 left-3 h-5 w-5 -translate-y-1/2 transform text-gray-400"
              />

              <input
                id="username"
                v-model="username"
                type="text"
                class="w-full rounded-lg border border-white/20 bg-white/10 py-3 pr-4 pl-10 text-white placeholder-gray-400 transition-all focus:border-transparent focus:ring-2 focus:ring-purple-500 focus:outline-none"
                placeholder="Введите имя пользователя"
                :disabled="loginMutation.isPending.value"
                autofocus
                autocomplete="username"
              />
            </div>
          </div>
          <div>
            <label
              for="password"
              class="mb-2 block text-sm font-medium text-gray-200"
            >
              Пароль
            </label>
            <div class="relative">
              <Lock
                class="absolute top-1/2 left-3 h-5 w-5 -translate-y-1/2 transform text-gray-400"
              />

              <input
                id="password"
                v-model="password"
                type="password"
                class="w-full rounded-lg border border-white/20 bg-white/10 py-3 pr-4 pl-10 text-white placeholder-gray-400 transition-all focus:border-transparent focus:ring-2 focus:ring-purple-500 focus:outline-none"
                placeholder="Введите пароль"
                :disabled="loginMutation.isPending.value"
                autocomplete="current-password"
              />
            </div>
          </div>

          <PurpleButton
            type="submit"
            :title="buttonTitle"
            :disabled="loginMutation.isPending.value"
          />
        </form>

        <div class="mt-6 text-center text-sm text-gray-400">
          <p>Если аккаунта нет, он будет создан автоматически</p>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/LoginPage.tsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { User, Lock } from "lucide-react";
import toast from "react-hot-toast";
import { useAuth } from "@/hooks/useAuth";

const LoginPage: React.FC = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!username.trim() || !password.trim()) {
      toast.error("Пожалуйста, заполните все поля");
      return;
    }

    setLoading(true);

    try {
      await login(username, password);
      toast.success("Добро пожаловать в игру!");

      navigate("/");
    } catch {
      toast.error("Ошибка входа");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl border border-white/20 p-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-white mb-2">
              The Last of Guss
            </h1>
            <p className="text-gray-300">Войдите, чтобы начать игру</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label
                htmlFor="username"
                className="block text-sm font-medium text-gray-200 mb-2"
              >
                Имя пользователя
              </label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />

                <input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Введите имя пользователя"
                  disabled={loading}
                />
              </div>
            </div>

            <div>
              <label
                htmlFor="password"
                className="block text-sm font-medium text-gray-200 mb-2"
              >
                Пароль
              </label>
              <div className="relative">
                <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />

                <input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full pl-10 pr-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all"
                  placeholder="Введите пароль"
                  disabled={loading}
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 px-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-semibold rounded-lg hover:from-purple-700 hover:to-pink-700 focus:outline-none focus:ring-2 focus:ring-purple-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 hover:cursor-pointer"
            >
              {loading ? "Вход..." : "Войти"}
            </button>
          </form>

          <div className="mt-6 text-center text-sm text-gray-400">
            <p>Если аккаунта нет, он будет создан автоматически</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;
