// frontend-vue/src/components/PurpleButton.vue
<script setup lang="ts">
interface Props {
  title: string;
}

const props = defineProps<Props>();
</script>

<template>
  <button
    :class="[
      'w-full rounded-lg px-4 py-3 font-semibold',
      'transform transition-all',
      'bg-gradient-to-r from-purple-600 to-pink-600 text-white',
      'hover:scale-105 hover:cursor-pointer hover:from-purple-700 hover:to-pink-700',
      'focus:ring-2 focus:ring-purple-500 focus:outline-none',
      'disabled:cursor-not-allowed disabled:opacity-50',
    ]"
  >
    <span>{{ props.title }}</span>
  </button>
</template>

// frontend/src/components/PurpleButton.tsx
import type { FC, ReactNode, ButtonHTMLAttributes } from "react";

interface PurpleButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  title: string;
  icon?: ReactNode;
}

const PurpleButton: FC<PurpleButtonProps> = ({ title, icon, ...rest }) => (
  <button
    className="w-full py-3 px-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-semibold rounded-lg hover:from-purple-700 hover:to-pink-700 focus:outline-none focus:ring-2 focus:ring-purple-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 hover:cursor-pointer"
    {...rest}
  >
    {icon}
    <span>{title}</span>
  </button>
);

export default PurpleButton;
