// frontend-vue/src/components/RoundPageHeader.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { ArrowLeft } from "lucide-vue-next";
import UserMenu from "./UserMenu.vue";

const router = useRouter();
</script>

<template>
  <div class="flex items-center justify-between">
    <button
      class="flex cursor-pointer items-center space-x-2 text-gray-400 transition-colors hover:text-white"
      @click="router.push('/rounds')"
    >
      <ArrowLeft class="h-5 w-5" />
      <span>Раунды</span>
    </button>

    <UserMenu />
  </div>
</template>

// frontend/src/components/RoundPageHeader.tsx
import clsx from "clsx";
import { useNavigate } from "react-router";
import { ArrowLeft } from "lucide-react";
import UserMenu from "./UserMenu";

const RoundPageHeader: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className={clsx("flex", "justify-between", "items-center")}>
      <button
        onClick={() => navigate("/rounds")}
        className={clsx(
          "flex",
          "items-center",
          "space-x-2",
          "text-gray-400",
          "hover:text-white",
          "transition-colors",
          "cursor-pointer"
        )}
      >
        <ArrowLeft className={clsx("w-5", "h-5")} />
        <span>Раунды</span>
      </button>

      <UserMenu />
    </div>
  );
};

export default RoundPageHeader;
