// frontend-vue/src/components/UserStats.vue
<script setup lang="ts">
import { defineProps } from "vue";
import { Trophy, Target } from "lucide-vue-next";

interface Props {
  taps: number;
  score: number;
}

defineProps<Props>();
</script>

<template>
  <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
    <div class="rounded-lg bg-white/5 p-4">
      <div class="flex items-center justify-center space-x-2 text-blue-400">
        <Target class="h-5 w-5" />
        <span class="font-medium">Мои тапы</span>
      </div>
      <div class="text-2xl font-bold text-white">{{ taps }}</div>
    </div>
    <div class="rounded-lg bg-white/5 p-4">
      <div class="flex items-center justify-center space-x-2 text-purple-400">
        <Trophy class="h-5 w-5" />
        <span class="font-medium">Мои очки</span>
      </div>
      <div class="text-2xl font-bold text-white">{{ score }}</div>
    </div>
  </div>
</template>

// frontend/src/components/UserStats.tsx
import { memo } from "react";
import { Trophy, Target } from "lucide-react";
import clsx from "clsx/lite";

interface Props {
  taps: number;
  score: number;
}

const UserStats: React.FC<Props> = memo(({ taps, score }) => (
  <div className={clsx("grid", "grid-cols-1", "sm:grid-cols-2", "gap-4")}>
    <div className={clsx("bg-white/5", "rounded-lg", "p-4")}>
      <div
        className={clsx(
          "flex",
          "items-center",
          "justify-center",
          "space-x-2",
          "text-blue-400"
        )}
      >
        <Target className={clsx("w-5", "h-5")} />
        <span className={clsx("font-medium")}>Мои тапы</span>
      </div>
      <div className={clsx("text-2xl", "font-bold", "text-white")}>{taps}</div>
    </div>
    <div className={clsx("bg-white/5", "rounded-lg", "p-4")}>
      <div
        className={clsx(
          "flex",
          "items-center",
          "justify-center",
          "space-x-2",
          "text-purple-400"
        )}
      >
        <Trophy className={clsx("w-5", "h-5")} />
        <span className={clsx("font-medium")}>Мои очки</span>
      </div>
      <div className={clsx("text-2xl", "font-bold", "text-white")}>{score}</div>
    </div>
  </div>
));

export default UserStats;
