// frontend/src/components/AuthGuard.tsx
import { useAtomValue } from "jotai";
import { isVerifyLoadingAtom, userAtom } from "@/store/authAtoms";
import LoadingState from "@/components/LoadingState";
import LoginPage from "@/pages/LoginPage";

interface AuthGuardProps {
  children: React.ReactNode;
}

const AuthGuard: React.FC<AuthGuardProps> = ({ children }) => {
  const user = useAtomValue(userAtom);
  const isLoading = useAtomValue(isVerifyLoadingAtom);

  if (isLoading) {
    return <LoadingState />;
  }

  if (!user) {
    return <LoginPage />;
  }

  return children;
};

export default AuthGuard;

// frontend-vue/src/components/AuthGuard.vue
<script setup lang="ts">
import { watch } from "vue";
import LoadingState from "@/components/LoadingState.vue";
import LoginPage from "@/pages/LoginPage.vue";
import { useAuthStore } from "@/store/authStore";
import { useVerifyQuery } from "@/queries/auth";

const authStore = useAuthStore();
const { data, isLoading } = useVerifyQuery(!!authStore.token);

watch(data, () => {
  if (data.value?.user) {
    authStore.setUser(data.value.user);
  }
});
</script>

<template>
  <LoadingState v-if="isLoading" />
  <template v-else>
    <slot v-if="!!authStore.user" />
    <LoginPage v-else />
  </template>
</template>
