// frontend/src/components/RoundCard.tsx
import { Clock } from "lucide-react";
import clsx from "clsx/lite";
import type { RoundWithStatus } from "@shared/types";
import { formatDate, formatTime } from "@shared/frontend/helpers/rounds";
import { getStatusInfo } from "@/utils/getStatusInfo";
import { useRoundTimer } from "@/hooks/useRoundTimer";

interface Props {
  round: RoundWithStatus;
  onClick: () => void;
  onTimeout: () => void;
}

const RoundCard: React.FC<Props> = ({ round, onClick, onTimeout }) => {
  const status = round.status.value;
  const timeLeft = useRoundTimer({
    initTimeLeft: round.status.timer,
    disabled: status === "finished",
    onTimeout,
  });

  const statusInfo = getStatusInfo(round.status?.value);
  const StatusIcon = statusInfo.icon;

  return (
    <div
      onClick={onClick}
      className={clsx(
        "bg-white/10",
        "backdrop-blur-lg",
        "rounded-xl",
        "p-6",
        "border",
        "border-white/20",
        "hover:border-purple-400/50",
        "cursor-pointer",
        "transition-all",
        "transform",
        "hover:shadow-2xl"
      )}
    >
      <div className={clsx("flex", "items-start", "justify-between")}>
        <div className={clsx("space-y-2", "max-w-full", "w-full")}>
          <div className={clsx("flex", "items-center", "space-x-3")}>
            <div
              className={clsx(
                "w-3",
                "h-3",
                "rounded-full",
                statusInfo.bgColorAlt,
                "shrink-0",
                "hidden",
                "sm:inline"
              )}
            ></div>
            <h3
              className={clsx(
                "text-white",
                "font-mono",
                "text-sm",
                "flex",
                "flex-col",
                "gap-0",
                "sm:flex-row",
                "sm:gap-2",
                "max-w-full"
              )}
            >
              <span>Round ID:</span>
              <span className={clsx("truncate")}>{round.id}</span>
            </h3>
          </div>
          <div className={clsx("space-y-1", "text-gray-300", "text-sm")}>
            <div>
              <span className={clsx("text-gray-400")}>Start:</span>{" "}
              {formatDate(round.startTime)}
            </div>
            <div>
              <span className={clsx("text-gray-400")}>End:</span>{" "}
              {formatDate(round.endTime)}
            </div>
          </div>
          <div className={clsx("border-t", "border-white/10", "my-4")}></div>
          <div className={clsx("flex", "items-center", "justify-between")}>
            <div
              className={clsx(
                "flex",
                "items-center",
                "space-x-2",
                "px-3",
                "py-1",
                "rounded-full",
                statusInfo.bgColor
              )}
            >
              <StatusIcon className={clsx("w-4", "h-4", statusInfo.color)} />
              <span
                className={clsx("text-sm", "font-medium", statusInfo.color)}
              >
                Статус: {statusInfo.title}
              </span>
            </div>

            {timeLeft && status !== "finished" ? (
              <div className={clsx("text-purple-400", "flex", "space-x-2")}>
                <Clock className={clsx("w-5", "h-5")} />
                <span className={clsx("font-mono", "text-sm")}>
                  {formatTime(timeLeft)}
                </span>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RoundCard;

// frontend-vue/src/components/RoundCard.vue
<script setup lang="ts">
import { computed, toRefs } from "vue";
import { Clock } from "lucide-vue-next";
import { formatDate, formatTime } from "@shared/frontend/helpers/rounds";
import { getStatusInfo } from "@/utils/getStatusInfo";
import { useRoundTimer } from "@/composables/useRoundTimer";
import type { RoundWithStatus } from "@shared/types";

interface Props {
  round: RoundWithStatus;
  onTimeout: () => void;
}

const props = defineProps<Props>();

const { round, onTimeout } = toRefs(props);
const status = computed(() => round.value.status.value);
const statusInfo = computed(() => getStatusInfo(round.value.status.value));
const startTime = computed(() => formatDate(round.value.startTime));
const endTime = computed(() => formatDate(round.value.endTime));

const initTimeLeft = computed(() => round.value.status.timer);
const isTimerDisabled = computed(() => status.value === "finished");
const timeLeft = useRoundTimer({
  initTimeLeft,
  disabled: isTimerDisabled,
  onTimeout: onTimeout.value,
});
const shouldDisplayTimer = computed(
  () => timeLeft.value > 0 && status.value !== "finished",
);
</script>

<template>
  <div
    :class="[
      'cursor-pointer rounded-xl border border-white/20 p-6',
      'bg-white/10 backdrop-blur-lg hover:border-purple-400/50 hover:shadow-2xl',
      'transform transition-all',
    ]"
  >
    <div class="flex items-start justify-between">
      <div class="w-full max-w-full space-y-2">
        <div class="flex items-center space-x-3">
          <div
            :class="[
              'hidden h-3 w-3 shrink-0 rounded-full sm:inline',
              statusInfo.bgColorAlt,
            ]"
          ></div>
          <h3
            class="flex max-w-full flex-col gap-0 font-mono text-sm text-white sm:flex-row sm:gap-2"
          >
            <span>Round ID:</span>
            <span class="truncate">{{ round.id }}</span>
          </h3>
        </div>
        <div class="space-y-1 text-sm text-gray-300">
          <div>
            <span class="text-gray-400">Start:</span>
            {{ startTime }}
          </div>
          <div>
            <span class="text-gray-400">End:</span>
            {{ endTime }}
          </div>
        </div>
        <div class="my-4 border-t border-white/10"></div>
        <div class="flex items-center justify-between">
          <div
            :class="[
              'flex items-center space-x-2 rounded-full px-3 py-1',
              statusInfo.bgColor,
            ]"
          >
            <component
              :is="statusInfo.icon"
              :class="['h-4 w-4', statusInfo.color]"
            />
            <span :class="['text-sm font-medium', statusInfo.color]">
              Статус: {{ statusInfo.title }}
            </span>
          </div>
          <div v-if="shouldDisplayTimer" class="flex space-x-2 text-purple-400">
            <Clock class="h-5 w-5" />
            <span class="font-mono text-sm">{{ formatTime(timeLeft) }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
